### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by Victoare** [vortigont/ESPAsyncButton#4]
Hi!
Thanks for this awesome library.
Wondering if the activation and event handling could be simplified even more for really simple usecases?

Thinking something like this:
```cpp
ESPAsyncButton button1(35, LOW);

void setup() {
  ESPAsyncButton.setup(); // Static method, ensures the loop registration and registers an internal ISR handler
  button1.onClick([](){ /* dowhatever */ }); // enables the click event, enables the button.
  button1.onMultiClick([](byte clicks){ /* dowhatever */ }); // enables the multiclick event.
  button1.onAutoRepeat(autorepeathandler); // register as function

  // to change the handler:
  button1.onClick([](){ /* dowhatever else */ });

  // to remove the handler, disable the event and disable the button if there are no more callbacks, something like this:
  button1.onClick(); 
  button1.onClick(NULL);
  button1.removeOnClick();
}

void autorepeathandler(gpio port, other params){
 ...
}
```
(sorry if the syntax is invalid, come from a c# environment and struggling a bit with the c++ literature :D)
Maybe ESPAsyncButton.setup(); can also be eliminated if an event registration could check if an initialization ran before.

**Comment by vortigont** [comment]
Hi @Victoare,
thanks for your feedback!
Actually I was trying to drift away for such approach to have callbacks attached to particular button instance and the main reason for this is that in such way it becomes really difficult to handle multi button cases like tracking when two buttons are pressed simultaneously, etc...
But agreed, such code style could be more easy to use/understand for simple cases, like one button or some basic tasks.
This could be easily implemented with this lib in user code with some container or derivative class.
I'll add to my TODO list to create such implementation and bundle it within the lib.

**Comment by Victoare** [comment]
Yes, your point is totally understandable.
I did (at least tried to do) something you mentioned.
It will be nice to have something ready in your lib.

**Comment by vortigont** [comment]
Let's keep it open as a reminder, I'll implement a reference use case for this anytime soon.

**Comment by Victoare** [comment]
Nice!

If I read it right this is the form, right?
```cpp
AsyncEventButton btn1(35, LOW);
AsyncEventButton btn2(0, LOW);

void setup(){
  AsyncEventButton::begin();
  btn1.onClick([](){ /* onClickHandle */ });
  btn2.onClick([](){ /* onClickHandle */ });
}
```

Or the begin() should be called on every instance?
```cpp
AsyncEventButton btn1(35, LOW);
AsyncEventButton btn2(0, LOW);

void setup(){
  btn1.begin();
  btn1.onClick([](){ /* onClickHandle */ });
  btn2.begin();
  btn2.onClick([](){ /* onClickHandle */ });
}
```

**Comment by vortigont** [comment]
No, you need to call begin() for each instance. It will subscribe object instance to the event loop and unsubscribe on instance destruction. Otherwise it will crash if event loop calls a dangling pointed object.
